#define STR_HEART0_BMP "bmp\\heart0.bmp"
#define STR_HEART1_BMP "bmp\\heart1.bmp"
#define STR_HEART2_BMP "bmp\\heart2.bmp"
#define STR_HEART3_BMP "bmp\\heart3.bmp"
#define STR_HEART4_BMP "bmp\\heart4.bmp"
#define STR_HEARTMASK_BMP "bmp\\heartmask.bmp"
#define STR_BUBBLEMASK_BMP "bmp\\bubblemask.bmp"
#define STR_BUBBLEHEARTS_BMP "bmp\\bubblehearts.bmp"
#define STR_BUBBLEVALENTINE_BMP "bmp\\bubblevalentine.bmp"
#define STR_BUBBLEILOVEYOU_BMP "bmp\\bubbleiloveyou.bmp"
#define STR_BUG1_BMP "bmp\\bug1.bmp"
#define STR_BUG2_BMP "bmp\\bug2.bmp"
#define STR_BUG3_BMP "bmp\\bug3.bmp"
#define STR_BUG1MASK_BMP "bmp\\bug1_mask.bmp"
#define STR_BUG2MASK_BMP "bmp\\bug2_mask.bmp"


#define WAV_ILOVEYOU "snd\\iloveyou.wav"
#define WAV_VALENTINE "snd\\valentine.wav"
